apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sonarr-pv"

