apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: sonarr
  name: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/sonarr-default: "true"
        io.kompose.service: sonarr
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/New_York
          image: lscr.io/linuxserver/sonarr:latest
          name: sonarr
          ports:
            - containerPort: 8989
              hostPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: sonarr-config
            - mountPath: /plex
              name: plex-volume
      restartPolicy: Always
      volumes:
        - name: sonarr-config
          persistentVolumeClaim:
            claimName: sonarr-pv-claim
        - name: plex-volume
          nfs:
            server: 192.168.1.155
            path: /volume1/Plex
            readOnly: false
