apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: overseerr-nfs
  name: overseerr-nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: overseerr-nfs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/overseerr-default: "true"
        io.kompose.service: overseerr-nfs
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/New_York
          image: lscr.io/linuxserver/overseerr:latest
          name: overseerr-nfs
          ports:
            - containerPort: 5055
              hostPort: 5055
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config-volume
      restartPolicy: Always
      volumes:
        - name: config-volume
          nfs:
            server: 192.168.1.155
            path: /volume1/k8s-overseerr
            readOnly: false
