apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  labels:
    app: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: ubuntu/apache2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: synologynas-volume
      volumes:
        - name: synologynas-volume
          nfs:
            server: 192.168.1.155
            path: /volume1/k8s-apache
            readOnly: false

